### ISSUE TITLE
How to point the database connection port?

### ISSUE THREAD

**Issue by sxaxin** [veelion/ezmysql#1]
My mysql server port is 8889 instead of 3306. How can I change it?

**Comment by veelion** [comment]
just add 'port'  when create connection:

db = ConnectionSync(
        host,
        database,
        user,
        password,
        port=8899
    )

for more arguments:
https://github.com/veelion/ezmysql/blob/1481de867142323a27747ac2989994d45a33821a/ezmysql/connection_sync.py#L11-L18
